### ISSUE TITLE
springboot error

### ISSUE THREAD

**Issue by tyuseman** [ximtech/altium-migrator#1]
While executing: docker run -p 5432:5432 -e PROFILE=docker-dev ximtech/altium-migrator

there are errors...

`
 ERROR [main] (SpringApplication.java:859) - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.lambda$callRunner$6(SpringApplication.java:797) ~[spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:66) ~[spring-core-6.1.8.jar:6.1.8]
        at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.8.jar:6.1.8]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774) [spring-boot-3.2.6.jar:3.2.6]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774) [spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:342) [spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) [spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) [spring-boot-3.2.6.jar:3.2.6]
        at altium.migrator.AltiumMigratorApplication.main(AltiumMigratorApplication.java:10) [classes/:1.1.0]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) [workspace/:?]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) [workspace/:?]
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) [workspace/:?]
Caused by: org.eclipse.jgit.api.errors.TransportException: Premature EOF
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:246) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:191) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at altium.migrator.service.GitRepositoryService.cloneRepositoryWithChangelog(GitRepositoryService.java:41) ~[classes/:1.1.0]
        at altium.migrator.service.MigrationCommandRunner.run(MigrationCommandRunner.java:27) ~[classes/:1.1.0]
        at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.8.jar:6.1.8]
        at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.8.jar:6.1.8]
        ... 22 more
Caused by: org.eclipse.jgit.errors.TransportException: Premature EOF
        at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:433) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:1551) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:325) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:316) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:288) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:180) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:191) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at altium.migrator.service.GitRepositoryService.cloneRepositoryWithChangelog(GitRepositoryService.java:41) ~[classes/:1.1.0]
        at altium.migrator.service.MigrationCommandRunner.run(MigrationCommandRunner.java:27) ~[classes/:1.1.0]
        at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.8.jar:6.1.8]
        at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.8.jar:6.1.8]
        ... 22 more
Caused by: java.io.IOException: Premature EOF
        at java.base/sun.net.www.http.ChunkedInputStream.fastRead(Unknown Source) ~[?:?]
        at java.base/sun.net.www.http.ChunkedInputStream.read(Unknown Source) ~[?:?]
        at java.base/java.io.FilterInputStream.read(Unknown Source) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source) ~[?:?]
        at org.eclipse.jgit.util.io.UnionInputStream.read(UnionInputStream.java:116) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.SideBandInputStream.read(SideBandInputStream.java:115) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1240) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1798) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at java.base/java.io.InputStream.read(Unknown Source) ~[?:?]
        at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:1061) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:983) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:534) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:170) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:495) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:1081) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.BasePackFetchConnection.doFetchV2(BasePackFetchConnection.java:519) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:399) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:1551) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:325) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:316) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:288) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:180) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:191) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
        at altium.migrator.service.GitRepositoryService.cloneRepositoryWithChangelog(GitRepositoryService.java:41) ~[classes/:1.1.0]
        at altium.migrator.service.MigrationCommandRunner.run(MigrationCommandRunner.java:27) ~[classes/:1.1.0]
        at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.2.6.jar:3.2.6]
        at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.8.jar:6.1.8]
        at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.8.jar:6.1.8]
        ... 22 more
        Suppressed: java.io.IOException: Premature EOF
                at java.base/sun.net.www.http.ChunkedInputStream.fastRead(Unknown Source) ~[?:?]
                at java.base/sun.net.www.http.ChunkedInputStream.read(Unknown Source) ~[?:?]
                at java.base/java.io.FilterInputStream.read(Unknown Source) ~[?:?]
                at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source) ~[?:?]
                at org.eclipse.jgit.util.io.UnionInputStream.read(UnionInputStream.java:116) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.SideBandInputStream.read(SideBandInputStream.java:115) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1240) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1798) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at java.base/java.io.InputStream.read(Unknown Source) ~[?:?]
                at org.eclipse.jgit.transport.PackParser$InflaterStream.close(PackParser.java:1820) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:1068) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:983) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:534) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:170) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:495) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:1081) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.BasePackFetchConnection.doFetchV2(BasePackFetchConnection.java:519) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:399) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:1551) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:325) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:316) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:288) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:180) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:191) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar:6.4.0.202211300538-r]
                at altium.migrator.service.GitRepositoryService.cloneRepositoryWithChangelog(GitRepositoryService.java:41) ~[classes/:1.1.0]
                at altium.migrator.service.MigrationCommandRunner.run(MigrationCommandRunner.java:27) ~[classes/:1.1.0]
                at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.2.6.jar:3.2.6]
                at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.8.jar:6.1.8]
                at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.8.jar:6.1.8]
                at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.8.jar:6.1.8]
                at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-3.2.6.jar:3.2.6]
                at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-3.2.6.jar:3.2.6]
                at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774) [spring-boot-3.2.6.jar:3.2.6]
                at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
                at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:?]
                at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
                at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
                at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
                at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
                at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
                at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
                at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774) [spring-boot-3.2.6.jar:3.2.6]
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:342) [spring-boot-3.2.6.jar:3.2.6]
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) [spring-boot-3.2.6.jar:3.2.6]
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) [spring-boot-3.2.6.jar:3.2.6]
                at altium.migrator.AltiumMigratorApplication.main(AltiumMigratorApplication.java:10) [classes/:1.1.0]
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
                at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
                at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) [workspace/:?]
                at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) [workspace/:?]
                at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) [workspace/:?]
`

I've downloaded the most outdated Docker Desktop available - [4.31.0](https://docs.docker.com/desktop/release-notes/#4310), but it doesn't help.

**Comment by ximtech** [comment]
Hi! This error: `org.eclipse.jgit.api.errors.TransportException: Premature EOF` 
Looks like jgit failed to clone or fetch Github repo because the HTTP connection was cut off before all data was received.
Can you please check that `https://github.com/ximtech/altium-library` is accessable and can be cloned?
